apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: mid-fluentd
  labels:
    app.kubernetes.io/name: fluentd
spec:
  mode: collector
  globalInputs:
  - forward:
      bind: 0.0.0.0
      port: 24224
  - customPlugin:
      config: |
        <source>
          @type prometheus
          bind 0.0.0.0
          port 2021
          metrics_path /metrics
        </source>
  replicas: 1
  image: kubesphere/fluentd:v1.15.3
  fluentdCfgSelector:
    matchLabels:
      config.fluentd.fluent.io/enabled: "true"
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFluentdConfig
metadata:
  name: fluentd-config
  labels:
    config.fluentd.fluent.io/enabled: "true"
spec:
  watchedNamespaces:
  - default
  - logging
  clusterFilterSelector:
    matchLabels:
      filter.fluentd.fluent.io/enabled: "true"
  clusterOutputSelector:
    matchLabels:
      output.fluentd.fluent.io/enabled: "true"

---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFilter
metadata:
  name: fluentd-filter
  labels:
    filter.fluentd.fluent.io/enabled: "true"
spec:
  filters:
  - customPlugin:
      config: |
        <source>
          @type prometheus
          bind 0.0.0.0
          port 2021
        </source>
  - recordTransformer:
      autoTypecast: true
      enableRuby: true
      records:
      - key: num
        value: "${record['log'].downcase.include?('ss') ? 1 : 0}"


---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
    - customPlugin:
        config: |
          <match **>
            @type copy
            <store>
              @type prometheus
              <metric>
                name log_count
                type counter
                desc the total num log
                key num
                <labels>
                  pod busybox
                </labels>
              </metric>
            </store>
            <store>
              @type stdout
            </store>
          </match>


