apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  annotations:
    avp.kubernetes.io/path: "k8s-kv/data/app/flask-demo"
type: Opaque
data:
  DB_NAME: ZGVtbw==
  DB_USERNAME: <db-user>
  DB_PASSWORD: <db-pass>
  DB_HOST: MTI3LjAuMC4x
  DB_PORT: OTUyNw==
