apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifest.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
    target:
      kind: Service
      name: flask-demo-helm
