---
# Source: flask-demo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-demo-helm
  labels:
    app: flask-demo-helm
    version: v1
spec:
  ports:
    - name: http-5000
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: flask-demo-helm
    version: v1
  type: NodePort
---
# Source: flask-demo/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-demo-helm
  labels:
    app: flask-demo-helm
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo-helm
      version: v1
  template:
    metadata:
      labels:
        app: flask-demo-helm
        version: v1
    spec:
      containers:
        - name: flask-demo
          image: bwei/flask-demo:ff91ebafa951b6839bea0c395c3de088480d42af
          ports:
            - name: http-5000
              containerPort: 5000
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_PORT
---
# Source: flask-demo/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "flask-demo-test-connection"
  labels:
    helm.sh/chart: flask-demo-0.1.0
    app.kubernetes.io/name: flask-demo
    app.kubernetes.io/instance: flask-demo
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['flask-demo:5000']
  restartPolicy: Never
