apiVersion: v1
kind: Secret
metadata:
  name: platform-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  name: cGxhdGZvcm0K
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206QmVlckxpaS9wbGF0Zm9ybS5naXQK
  sshPrivateKey: L1VzZXJzL2J3ZWlsaS8uc3NoL2lkX2VkMjU1MTkK
  insecure: dHJ1ZQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: governed-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  name: Z292ZXJuZWQK
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206QmVlckxpaS9nb3Zlcm5lZC5naXQK
  sshPrivateKey: L1VzZXJzL2J3ZWlsaS8uc3NoL2lkX2VkMjU1MTkK
  insecure: dHJ1ZQ==

