apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: kustomize-template-plugin
      generate:
        command: ["bash", "-c"]
        args: ['argocd-cmp "kustomize"; kustomize build .']
      discover:
        fileName: "./kustomization.yaml"
    - name: helm-kustomize-template-plugin
      generate:
        command: ["bash", "-c"]
        args: ['argocd-cmp "helm"; kustomize build .']
      discover:
        fileName: "./kustomization.yaml"