apiVersion: v1
kind: Secret
metadata:
  name: platform-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  name: cGxhdGZvcm0K
  type: Z2l0
  project: ZGVmYXVsdA==
  url: Z2l0QGdpdGh1Yi5jb206QmVlckxpaS9wbGF0Zm9ybS5naXQ=
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBb2hwdDllNTdsczAyendPTHlzclJ2S1RwMTBBVDNBZkROZjVnWnRsRjE0d0FBQUpqaFpLVHk0V1NrCjhnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQW9ocHQ5ZTU3bHMwMnp3T0x5c3JSdktUcDEwQVQzQWZETmY1Z1p0bEYxNHcKQUFBRUFIbk5HcE9ETVJxOFFCUWVwc004KzROZ1ZySUI4Z0hUSy85T3d6Qnk4MUhDaUdtMzE3bnVXelRiUEE0dkt5dEc4cApPblhRQlBjQjhNMS9tQm0yVVhYakFBQUFFRGN6TlRrMk5EQXpNMEJ4Y1M1amIyMEJBZ01FQlE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K


---

apiVersion: v1
kind: Secret
metadata:
  name: governed-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  name: Z292ZXJuZWQK
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206QmVlckxpaS9nb3Zlcm5lZC5naXQ=
  project: ZGVmYXVsdA==
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBb2hwdDllNTdsczAyendPTHlzclJ2S1RwMTBBVDNBZkROZjVnWnRsRjE0d0FBQUpqaFpLVHk0V1NrCjhnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQW9ocHQ5ZTU3bHMwMnp3T0x5c3JSdktUcDEwQVQzQWZETmY1Z1p0bEYxNHcKQUFBRUFIbk5HcE9ETVJxOFFCUWVwc004KzROZ1ZySUI4Z0hUSy85T3d6Qnk4MUhDaUdtMzE3bnVXelRiUEE0dkt5dEc4cApPblhRQlBjQjhNMS9tQm0yVVhYakFBQUFFRGN6TlRrMk5EQXpNMEJ4Y1M1amIyMEJBZ01FQlE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K

