apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifest.yaml
  - argo-repo-secret.yaml
  - nodeport.yaml
  - repo-server-role.yaml
  - repo-server-rolebinding.yaml

patchesStrategicMerge:
  - argocd-cm-patch.yaml
  - repo-server-deployment-patch.yaml


