apiVersion: v1
kind: Secret
metadata:
  name: platform-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    avp.kubernetes.io/path: "k8s-kv/data/platform/repo-vault"
type: Opaque
data:
  name: cGxhdGZvcm0K
  type: Z2l0
  project: ZGVmYXVsdA==
  url: Z2l0QGdpdGh1Yi5jb206QmVlckxpaS9wbGF0Zm9ybS5naXQ=
  sshPrivateKey: <repo-key>


---

apiVersion: v1
kind: Secret
metadata:
  name: governed-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    avp.kubernetes.io/path: "k8s-kv/data/platform/repo-vault"
type: Opaque
data:
  name: Z292ZXJuZWQK
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206QmVlckxpaS9nb3Zlcm5lZC5naXQ=
  project: ZGVmYXVsdA==
  sshPrivateKey: <repo-key>

