apiVersion: v1
kind: Secret
metadata:
 name: vault-platform-cred
 namespace: argocd
 annotations:
   avp.kubernetes.io/path: "k8s-kv/data/platform/platform-vault"
type: Opaque
data:
  VAULT_ADDR: cGxhdGZvcm0tdmF1bHQucGxhdGZvcm0tdmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwK
  VAULT_TOKEN: <platform-vault-token>
  AVP_TYPE: dmF1bHQ=
  AVP_AUTH_TYPE: dG9rZW4=

---

apiVersion: v1
kind: Secret
metadata:
 name: vault-app-cred
 namespace: argocd
 annotations:
   avp.kubernetes.io/path: "k8s-kv/data/platform/app-vault"
type: Opaque
data:
  VAULT_ADDR: YXBwLXZhdWx0LmFwcC12YXVsdC5zdmMuY2x1c3Rlci5sb2NhbAo=
  VAULT_TOKEN: <platform-vault-token>
  AVP_TYPE: dmF1bHQ=
  AVP_AUTH_TYPE: dG9rZW4=


